version: "3.9"
services:
  service-a:
    build: ../service
    hostname: service-a
    environment:
      FLASK_RUN_PORT: "5000"
      SCRAPE_TAPE: '/var/lib/scrapes.yaml'
    volumes:
      - ./service-a.yaml:/var/lib/scrapes.yaml
    ports:
      - "55000:5000"
  prometheus:
    image: prom/prometheus:latest
    entrypoint: ["/bin/prometheus", "--config.file=/opt/prometheus/prometheus.yml", "--query.lookback-delta=2h"]
    ports:
      - "55055:9090"
    volumes:
      - ./prometheus.yml:/opt/prometheus/prometheus.yml
      - promdata:/prometheus:z

volumes:
  promdata: